//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBook.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceWeb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebBook.Resource.ResourceWeb", typeof(ResourceWeb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئات.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفعيل الحساب.
        /// </summary>
        public static string lbActiveUser {
            get {
                return ResourceManager.GetString("lbActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string lbAddress {
            get {
                return ResourceManager.GetString("lbAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المؤلف.
        /// </summary>
        public static string lbAuthor {
            get {
                return ResourceManager.GetString("lbAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعة الكتب.
        /// </summary>
        public static string lbBooks {
            get {
                return ResourceManager.GetString("lbBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        public static string lbbtnChangePassword {
            get {
                return ResourceManager.GetString("lbbtnChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string lbbtnDelete {
            get {
                return ResourceManager.GetString("lbbtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string lbbtnEdit {
            get {
                return ResourceManager.GetString("lbbtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الصفحة.
        /// </summary>
        public static string lbbtnEditPage {
            get {
                return ResourceManager.GetString("lbbtnEditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string lbbtnSave {
            get {
                return ResourceManager.GetString("lbbtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة كتاب.
        /// </summary>
        public static string lbBtnSaveNewBook {
            get {
                return ResourceManager.GetString("lbBtnSaveNewBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضف فئة جديدة.
        /// </summary>
        public static string lbBtnSaveNewCategory {
            get {
                return ResourceManager.GetString("lbBtnSaveNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضاقة مجموعة.
        /// </summary>
        public static string lbbtnSaveNewRole {
            get {
                return ResourceManager.GetString("lbbtnSaveNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انشاء عارض.
        /// </summary>
        public static string lbbtnSaveNewSlider {
            get {
                return ResourceManager.GetString("lbbtnSaveNewSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة فئة فرعية.
        /// </summary>
        public static string lbBtnSaveNewSubCategory {
            get {
                return ResourceManager.GetString("lbBtnSaveNewSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة مستخدم جديد.
        /// </summary>
        public static string lbbtnSaveNewUser {
            get {
                return ResourceManager.GetString("lbbtnSaveNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الغاء.
        /// </summary>
        public static string lbcancelButtonText {
            get {
                return ResourceManager.GetString("lbcancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكنك التراجع عن هذا!.
        /// </summary>
        public static string lbCantBack {
            get {
                return ResourceManager.GetString("lbCantBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعة الفئات.
        /// </summary>
        public static string lbCategories {
            get {
                return ResourceManager.GetString("lbCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعد كلمة المرور.
        /// </summary>
        public static string lbComparePassword {
            get {
                return ResourceManager.GetString("lbComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم احذف هذا!.
        /// </summary>
        public static string lbConfirmDelete {
            get {
                return ResourceManager.GetString("lbConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الاتصال.
        /// </summary>
        public static string lbContactNumber {
            get {
                return ResourceManager.GetString("lbContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة عارض .
        /// </summary>
        public static string lbCreateSlider {
            get {
                return ResourceManager.GetString("lbCreateSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة مستخدم جديد.
        /// </summary>
        public static string lbCreateUser {
            get {
                return ResourceManager.GetString("lbCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة التحكم.
        /// </summary>
        public static string lbDashboard {
            get {
                return ResourceManager.GetString("lbDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        public static string lbDate {
            get {
                return ResourceManager.GetString("lbDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف الكتاب بنجاح.
        /// </summary>
        public static string lbDeleteBookSuccess {
            get {
                return ResourceManager.GetString("lbDeleteBookSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف الفئة بنجاح.
        /// </summary>
        public static string lbDeleteCatgorySuccess {
            get {
                return ResourceManager.GetString("lbDeleteCatgorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الحذف.
        /// </summary>
        public static string lbDeleteErrorTittle {
            get {
                return ResourceManager.GetString("lbDeleteErrorTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف مجموعة المستخدم..
        /// </summary>
        public static string lbDeleteRoleSuccess {
            get {
                return ResourceManager.GetString("lbDeleteRoleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف الفئة الفرعية بنجاح.
        /// </summary>
        public static string lbDeleteSubCatgorySuccess {
            get {
                return ResourceManager.GetString("lbDeleteSubCatgorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف.
        /// </summary>
        public static string lbDeleteSuccess {
            get {
                return ResourceManager.GetString("lbDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حذف المستخدم.
        /// </summary>
        public static string lbDeleteUserError {
            get {
                return ResourceManager.GetString("lbDeleteUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف المستخدم.
        /// </summary>
        public static string lbDeleteUserSuccess {
            get {
                return ResourceManager.GetString("lbDeleteUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الكتاب.
        /// </summary>
        public static string lbDescBook {
            get {
                return ResourceManager.GetString("lbDescBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الفئة.
        /// </summary>
        public static string lbDescCategory {
            get {
                return ResourceManager.GetString("lbDescCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الموقع.
        /// </summary>
        public static string lbDescSetting {
            get {
                return ResourceManager.GetString("lbDescSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل بيانات المستخدم.
        /// </summary>
        public static string lbEditDataUser {
            get {
                return ResourceManager.GetString("lbEditDataUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الصفحة.
        /// </summary>
        public static string lbEditPage {
            get {
                return ResourceManager.GetString("lbEditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تعديل الاعدادات بنجاح.
        /// </summary>
        public static string lbEditSettingError {
            get {
                return ResourceManager.GetString("lbEditSettingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل الاعدادات بنجاح.
        /// </summary>
        public static string lbEditSettingSuccess {
            get {
                return ResourceManager.GetString("lbEditSettingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل العارض.
        /// </summary>
        public static string lbEditSlider {
            get {
                return ResourceManager.GetString("lbEditSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل.
        /// </summary>
        public static string lbEditSuccess {
            get {
                return ResourceManager.GetString("lbEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        public static string lbEmail {
            get {
                return ResourceManager.GetString("lbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        public static string lbEmailUser {
            get {
                return ResourceManager.GetString("lbEmailUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        public static string lbError {
            get {
                return ResourceManager.GetString("lbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم انشاء الكتاب بنجاح.
        /// </summary>
        public static string lbErrorCreateBook {
            get {
                return ResourceManager.GetString("lbErrorCreateBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظ الفئة بنجاح.
        /// </summary>
        public static string lbErrorCreateCategory {
            get {
                return ResourceManager.GetString("lbErrorCreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم انشاء العارض.
        /// </summary>
        public static string lbErrorCreateSlider {
            get {
                return ResourceManager.GetString("lbErrorCreateSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظ الفئة الفرعية بنجاح.
        /// </summary>
        public static string lbErrorCreateSubCategory {
            get {
                return ResourceManager.GetString("lbErrorCreateSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تعديل الكتاب بنجاح.
        /// </summary>
        public static string lbErrorEditBook {
            get {
                return ResourceManager.GetString("lbErrorEditBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تديل الفئة بنجاح.
        /// </summary>
        public static string lbErrorEditCategory {
            get {
                return ResourceManager.GetString("lbErrorEditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تعديل العارض بنجاح.
        /// </summary>
        public static string lbErrorEditSlider {
            get {
                return ResourceManager.GetString("lbErrorEditSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تعديل الفئة الفرعية بنجاح.
        /// </summary>
        public static string lbErrorEditSubCategory {
            get {
                return ResourceManager.GetString("lbErrorEditSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء اختيار ملف pdf .
        /// </summary>
        public static string lbErrorSelectPdf {
            get {
                return ResourceManager.GetString("lbErrorSelectPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحدث.
        /// </summary>
        public static string lbEvents {
            get {
                return ResourceManager.GetString("lbEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الرئيسية.
        /// </summary>
        public static string lbHomePage {
            get {
                return ResourceManager.GetString("lbHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة الكتاب.
        /// </summary>
        public static string lbImageBook {
            get {
                return ResourceManager.GetString("lbImageBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة.
        /// </summary>
        public static string lbImagelUser {
            get {
                return ResourceManager.GetString("lbImagelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة.
        /// </summary>
        public static string lbImagePage {
            get {
                return ResourceManager.GetString("lbImagePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة العارض.
        /// </summary>
        public static string lbImageSlider {
            get {
                return ResourceManager.GetString("lbImageSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة المؤلف.
        /// </summary>
        public static string lbImgAuthor {
            get {
                return ResourceManager.GetString("lbImgAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط الفيسبوك.
        /// </summary>
        public static string lbLinkFacebook {
            get {
                return ResourceManager.GetString("lbLinkFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط الانستقرام.
        /// </summary>
        public static string lbLinkInstagram {
            get {
                return ResourceManager.GetString("lbLinkInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط لينكد ان.
        /// </summary>
        public static string lbLinkLinkedin {
            get {
                return ResourceManager.GetString("lbLinkLinkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط الموقع.
        /// </summary>
        public static string lbLinkLocation {
            get {
                return ResourceManager.GetString("lbLinkLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط تويتر.
        /// </summary>
        public static string lbLinkTwitter {
            get {
                return ResourceManager.GetString("lbLinkTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشعار.
        /// </summary>
        public static string lbLogoSetting {
            get {
                return ResourceManager.GetString("lbLogoSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة الكتب.
        /// </summary>
        public static string lbManageBook {
            get {
                return ResourceManager.GetString("lbManageBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس لديك صلاحية لهذه الصفحة.
        /// </summary>
        public static string lbMsgDenied {
            get {
                return ResourceManager.GetString("lbMsgDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل مجموعة المستخدم بنجاح.
        /// </summary>
        public static string lbMsgEdit {
            get {
                return ResourceManager.GetString("lbMsgEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تعديل مجموعة المستخدم.
        /// </summary>
        public static string lbMsgEditError {
            get {
                return ResourceManager.GetString("lbMsgEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الحفظ بنجاح.
        /// </summary>
        public static string lbMsgError {
            get {
                return ResourceManager.GetString("lbMsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم انشاء مستخدم جديد.
        /// </summary>
        public static string lbMsgErrorCreate {
            get {
                return ResourceManager.GetString("lbMsgErrorCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حذف الكتاب بنجاح.
        /// </summary>
        public static string lbMsgErrorDeleteBook {
            get {
                return ResourceManager.GetString("lbMsgErrorDeleteBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  لم يتم حذف الفئة.
        /// </summary>
        public static string lbMsgErrorDeleteCategory {
            get {
                return ResourceManager.GetString("lbMsgErrorDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حذف العملية بنجاح.
        /// </summary>
        public static string lbMsgErrorDeleteCategoryLog {
            get {
                return ResourceManager.GetString("lbMsgErrorDeleteCategoryLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حذف العارض بنجاح.
        /// </summary>
        public static string lbMsgErrorDeleteSlider {
            get {
                return ResourceManager.GetString("lbMsgErrorDeleteSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حذف الفئة الفرعية بنجاح.
        /// </summary>
        public static string lbMsgErrorDeleteSubCategory {
            get {
                return ResourceManager.GetString("lbMsgErrorDeleteSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تعديل بيانات المستخدم.
        /// </summary>
        public static string lbMsgErrorEdit {
            get {
                return ResourceManager.GetString("lbMsgErrorEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تعديل كلمة المرور.
        /// </summary>
        public static string lbMsgErrorEditPassword {
            get {
                return ResourceManager.GetString("lbMsgErrorEditPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في كلمة المرور او الايميل.
        /// </summary>
        public static string lbMsgErrorLogin {
            get {
                return ResourceManager.GetString("lbMsgErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الكتاب موجود بالفعل.
        /// </summary>
        public static string lbMsgNameBookExists {
            get {
                return ResourceManager.GetString("lbMsgNameBookExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفئة موجود بالفعل.
        /// </summary>
        public static string lbMsgNameCategoryExists {
            get {
                return ResourceManager.GetString("lbMsgNameCategoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفئة الفرعية موجود بالفعل.
        /// </summary>
        public static string lbMsgNameSubCategoryExists {
            get {
                return ResourceManager.GetString("lbMsgNameSubCategoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ مجموعة المستخدم بنجاح.
        /// </summary>
        public static string lbMsgSuccess {
            get {
                return ResourceManager.GetString("lbMsgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم انشاء مستخدم جديد بنجاح.
        /// </summary>
        public static string lbMsgSuccessCreate {
            get {
                return ResourceManager.GetString("lbMsgSuccessCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف الكتاب بنجاح.
        /// </summary>
        public static string lbMsgSuccessDeleteBook {
            get {
                return ResourceManager.GetString("lbMsgSuccessDeleteBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف الفئة بنجاح.
        /// </summary>
        public static string lbMsgSuccessDeleteCategory {
            get {
                return ResourceManager.GetString("lbMsgSuccessDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف العملية ينجاح.
        /// </summary>
        public static string lbMsgSuccessDeleteCategoryLog {
            get {
                return ResourceManager.GetString("lbMsgSuccessDeleteCategoryLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف العارض بنجاح.
        /// </summary>
        public static string lbMsgSuccessDeleteSlider {
            get {
                return ResourceManager.GetString("lbMsgSuccessDeleteSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف الفئة الفرعية بنجاح.
        /// </summary>
        public static string lbMsgSuccessDeleteSubCategory {
            get {
                return ResourceManager.GetString("lbMsgSuccessDeleteSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل بيانات المستخدم بنجاح.
        /// </summary>
        public static string lbMsgSuccessEdit {
            get {
                return ResourceManager.GetString("lbMsgSuccessEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل كلمة المرور بنجاح.
        /// </summary>
        public static string lbMsgSuccessEditPassword {
            get {
                return ResourceManager.GetString("lbMsgSuccessEditPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الكتاب.
        /// </summary>
        public static string lbNameBook {
            get {
                return ResourceManager.GetString("lbNameBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفئة.
        /// </summary>
        public static string lbNameCategory {
            get {
                return ResourceManager.GetString("lbNameCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الصفحة.
        /// </summary>
        public static string lbNamePage {
            get {
                return ResourceManager.GetString("lbNamePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المجموعة.
        /// </summary>
        public static string lbNameRole {
            get {
                return ResourceManager.GetString("lbNameRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الموقع.
        /// </summary>
        public static string lbNameSetting {
            get {
                return ResourceManager.GetString("lbNameSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العارض.
        /// </summary>
        public static string lbNameSlider {
            get {
                return ResourceManager.GetString("lbNameSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفئة الفرعية.
        /// </summary>
        public static string lbNameSubCategory {
            get {
                return ResourceManager.GetString("lbNameSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string lbNameUser {
            get {
                return ResourceManager.GetString("lbNameUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسنا.
        /// </summary>
        public static string lbOk {
            get {
                return ResourceManager.GetString("lbOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الصفحة.
        /// </summary>
        public static string lbPageDesc {
            get {
                return ResourceManager.GetString("lbPageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحات.
        /// </summary>
        public static string lbPages {
            get {
                return ResourceManager.GetString("lbPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string lbPasswordUser {
            get {
                return ResourceManager.GetString("lbPasswordUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف.
        /// </summary>
        public static string lbPdf {
            get {
                return ResourceManager.GetString("lbPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تعديل الصفحة بنجاح.
        /// </summary>
        public static string lbPgeEditError {
            get {
                return ResourceManager.GetString("lbPgeEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل الصفحة بنجاح.
        /// </summary>
        public static string lbPgeEditSuccess {
            get {
                return ResourceManager.GetString("lbPgeEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اظهار للمستخدمين.
        /// </summary>
        public static string lbPublish {
            get {
                return ResourceManager.GetString("lbPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعة المستخدمين.
        /// </summary>
        public static string lbRoleUser {
            get {
                return ResourceManager.GetString("lbRoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختار الفئة.
        /// </summary>
        public static string lbSelectCategory {
            get {
                return ResourceManager.GetString("lbSelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختيار دور.
        /// </summary>
        public static string lbSelectRole {
            get {
                return ResourceManager.GetString("lbSelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختار الفئة الفرعية.
        /// </summary>
        public static string lbSelectSubCategory {
            get {
                return ResourceManager.GetString("lbSelectSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعدادات الموقع.
        /// </summary>
        public static string lbSettings {
            get {
                return ResourceManager.GetString("lbSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال صورة.
        /// </summary>
        public static string lbSliderRequire {
            get {
                return ResourceManager.GetString("lbSliderRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العارض.
        /// </summary>
        public static string lbSliders {
            get {
                return ResourceManager.GetString("lbSliders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئات الفرعية.
        /// </summary>
        public static string lbSubCategories {
            get {
                return ResourceManager.GetString("lbSubCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نجاح.
        /// </summary>
        public static string lbSuccess {
            get {
                return ResourceManager.GetString("lbSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم انشاء الكتاب بنجاح.
        /// </summary>
        public static string lbSuccessCreateBook {
            get {
                return ResourceManager.GetString("lbSuccessCreateBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم انشاء الفئة بنجاح.
        /// </summary>
        public static string lbSuccessCreateCategory {
            get {
                return ResourceManager.GetString("lbSuccessCreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم انشاء العارض بنجاح.
        /// </summary>
        public static string lbSuccessCreateSlider {
            get {
                return ResourceManager.GetString("lbSuccessCreateSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم انشاء الفئة الفرعية بنجاح.
        /// </summary>
        public static string lbSuccessCreateSubCategory {
            get {
                return ResourceManager.GetString("lbSuccessCreateSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل الكتاب بنجاح.
        /// </summary>
        public static string lbSuccessEditBook {
            get {
                return ResourceManager.GetString("lbSuccessEditBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل الفئة بنجاح.
        /// </summary>
        public static string lbSuccessEditCategory {
            get {
                return ResourceManager.GetString("lbSuccessEditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل العارض بنجاح.
        /// </summary>
        public static string lbSuccessEditSlider {
            get {
                return ResourceManager.GetString("lbSuccessEditSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل الفئة الفرعية بنجاح.
        /// </summary>
        public static string lbSuccessEditSubCategory {
            get {
                return ResourceManager.GetString("lbSuccessEditSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متأكد؟.
        /// </summary>
        public static string lbSure {
            get {
                return ResourceManager.GetString("lbSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 403.
        /// </summary>
        public static string lbSymbolDenied {
            get {
                return ResourceManager.GetString("lbSymbolDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حذف مجموعة المستخدم بنجاح.
        /// </summary>
        public static string lbTittleDeleteRoleError {
            get {
                return ResourceManager.GetString("lbTittleDeleteRoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف مجموعة المستخدم بنجاح.
        /// </summary>
        public static string lbTittleDeleteRoleSuccess {
            get {
                return ResourceManager.GetString("lbTittleDeleteRoleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل.
        /// </summary>
        public static string lbTittleEdit {
            get {
                return ResourceManager.GetString("lbTittleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم التعديل.
        /// </summary>
        public static string lbTittleEditError {
            get {
                return ResourceManager.GetString("lbTittleEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل اسم المجموعة.
        /// </summary>
        public static string lbTittleEditRole {
            get {
                return ResourceManager.GetString("lbTittleEditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الحفظ.
        /// </summary>
        public static string lbTittleError {
            get {
                return ResourceManager.GetString("lbTittleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ.
        /// </summary>
        public static string lbTittleSuccess {
            get {
                return ResourceManager.GetString("lbTittleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين .
        /// </summary>
        public static string lbUsers {
            get {
                return ResourceManager.GetString("lbUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع.
        /// </summary>
        public static string lbWebsite {
            get {
                return ResourceManager.GetString("lbWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمليات على الكتب.
        /// </summary>
        public static string LogBooks {
            get {
                return ResourceManager.GetString("LogBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمليات على الفئات.
        /// </summary>
        public static string LogCategories {
            get {
                return ResourceManager.GetString("LogCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمليات على الفئات الفرعية.
        /// </summary>
        public static string LogSubCategories {
            get {
                return ResourceManager.GetString("LogSubCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الكتاب.
        /// </summary>
        public static string tittleEditBook {
            get {
                return ResourceManager.GetString("tittleEditBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الفئة.
        /// </summary>
        public static string tittleEditCategory {
            get {
                return ResourceManager.GetString("tittleEditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الفئة الفرعية.
        /// </summary>
        public static string tittleEditSubCategory {
            get {
                return ResourceManager.GetString("tittleEditSubCategory", resourceCulture);
            }
        }
    }
}
